#######################
# Environment Variables

export EDITOR=$(which nvim)

PATH=~/.local/bin:$PATH

#######################
# PS1

parse_git_branch() {
     git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

BOLD=`tput bold`
BLUE="\[$(tput setaf 4)\]"
GREEN="\[$(tput setaf 2)\]"
RESET="\[$(tput sgr0)\]"

PS1="(${BOLD}${GREEN}\u${RESET}) ${BOLD}${GREEN}\w${BLUE}\$(parse_git_branch) ${RESET}\$ "

#######################
# Sourced

source $SYSTEM_ROOT/universal/aliases.bash
